export { default as arrow } from './arrow.png'
export { default as googleIcon } from './google-icon.png'
export { default as facebookIcon } from './facebook-icon.png'
export { default as eye } from './eye.png'
export { default as shoppingCart } from './shopping-cart.png'
